desktop:
  hosts:
    localhost:
      vars:
        ansible_host: localhost
        connection: local
        ansible_connection: local
        ansible_python_interpreter: "{{ansible_playbook_python}}"
