# Flatpak is already installed by default, we just need to add to it
- hosts: desktop
  become: false
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Install DNF Plugins
      become: true 
      dnf:
        name: dnf-plugins-core
    - name: Add Docker Repo
      become: true
      command:
        cmd: |
          dnf config-manager \
            --add-repo \
            https://download.docker.com/linux/fedora/docker-ce.repo 
        args:
          creates: /yum/repos.d/docker-ce.repo
    - name: Install Docker
      become: true
      dnf:
        name:
          - docker-ce 
          - docker-ce-cli 
          - containerd.io 
          - docker-compose-plugin

    - name: Setup ID Maps
      blockinfile:
        path: "{{ item }}"
        block: |
          {{user_login}}:100000:65536
      loop:
        - /etc/subuid
        - /etc/suggid

    - name: Run Rootless Setup
      command: dockerd-rootless-setuptool.sh install
      args:
        creates: /home/{{user_login}}/.config/systemd/user/docker.service 

    - name: Enable and Start User Rootless Docker Sytemd Service
      systemd:
        name: docker
        start: started
        enabled: yes
        scope: user
