# DisplayLink is used by USB Docks for Extra Monitors
# This RPM will install everything and it pretty much just works
- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Install DisplayLink RPM
      dnf:
        name: "https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v6.1.0-2/fedora-40-displaylink-1.14.7-4.github_evdi.x86_64.rpm"
        disable_gpg_check: true
