# DisplayLink is used by USB Docks for Extra Monitors
# This RPM will install everything and it pretty much just works
- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Install DisplayLink RPM
      dnf:
        name: "https://github.com/displaylink-rpm/displaylink-rpm/releases/download/v5.8.0-2/fedora-39-displaylink-1.14.3-1.github_evdi.x86_64.rpm" 
        disable_gpg_check: true
