---
- name: Prepare containers for Ansible management
  hosts: containers
  gather_facts: false
  tasks:
    - name: Wait for containers to be reachable
      wait_for_connection:
        delay: 5
        timeout: 300

    - name: Install Python if not present (for Ubuntu/Debian)
      raw: test -e /usr/bin/python3 || (apt-get update && apt-get install -y python3)
      when: ansible_pkg_mgr is not defined or ansible_pkg_mgr == "apt"
      changed_when: false

    - name: Install Python if not present (for Fedora)
      raw: test -e /usr/bin/python3 || (dnf install -y python3)
      when: ansible_pkg_mgr is defined and ansible_pkg_mgr == "dnf"
      changed_when: false

    - name: Gather facts after Python installation
      setup:

    - name: Install essential packages
      package:
        name:
          - sudo
          - python3-pip
          - curl
          - vim
        state: present

    - name: Ensure sudoers.d directory exists
      file:
        path: /etc/sudoers.d
        state: directory
        mode: '0755'

    - name: Configure passwordless sudo for default user
      copy:
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ ansible_user }}"
        mode: '0440'
        validate: 'visudo -cf %s'