- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Enable LXD Copr Repository
      community.general.copr:
        name: "@ganto/lxc4"

    - name: Install Packages
      package:
        name:
        - lxc
        - lxc-templates

    - name: Add firewall rule for LXD to allow IP allocation and network access
      firewalld:
        zone: trusted
        state: enabled
        interface: lxdbr0
        permanent: yes
        immediate: true

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    - name: Setup Service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - lxc-net
        - lxc
