# Git is already installed as it was used to clone this repo,
# so we just need to configure it
- hosts: desktop
  become: false
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Setup Git Config - user
      shell: |
        git config --global user.email "{{ user_email }}"
        git config --global user.name "{{ user_name }}"
        git config --global color.ui auto
        git config --global push.default simple;
        git config --global help.autocorrect 30;

    - name: Set up Global Git Ignores
      blockinfile:
        create: true
        block: |
          /.idea
          *.secret
          /untracked
          /vendor
        path: "~/.config/git/ignore"

    - name: Enable Git Bash Prompt
      shell: "git clone https://github.com/magicmonty/bash-git-prompt.git ~/.bash-git-prompt --depth=1"
      args:
        creates: /home/{{ user_login }}/.bash-git-prompt/.git/config

    - name: Update ~/.bashrc File for the Bash Git Prompt
      blockinfile:
        path: /home/{{ user_login }}/.bashrc
        marker: "# {mark} ANSIBLE MANAGED: Git Bash Prompt"
        block: |
          GIT_PROMPT_ONLY_IN_REPO=1
          GIT_PROMPT_THEME=Solarized
          GIT_PROMPT_START=$PS1
          source ~/.bash-git-prompt/gitprompt.sh
