- hosts: desktop
  name: LXC Install Config
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Enable LXD Copr Repository
      community.general.copr:
        name: "ganto/lxc4"

    - name: Install Packages
      package:
        name:
        - lxc
        - lxc-templates

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive


    - name: Setup LXC Service
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - lxc

    - name: Switch lxcbr0 to trusted firewall zone
      command: nmcli connection modify lxcbr0 connection.zone trusted

    # This one doesn't seem to take effect and might need to be re run at some later point
    # If this hasn't taken effect, containers can be started but they wont get an IP address
    - name: Firewalld trusted
      shell: |
        firewall-cmd --zone=trusted --change-interface=lxcbr0 --permanent
        firewall-cmd --reload

    - name: Create Insecure SSH Key for Connecting to Container
      become: true
      become_user: "{{ user_login }}"
      shell: ssh-keygen -t rsa -f ~/.ssh/id_lxc -q -P ""
      args:
        creates: "/home/{{ user_login }}/.ssh/id_lxc"

    - name: Set up SSH Config for LXC Containers
      blockinfile:
        marker: "# {mark} LXC Containers Insecure Key"
        path: "/home/{{ user_login }}/.ssh/config"
        create: true
        owner: "{{ user_login }}"
        group: "{{ user_login }}"
        block: |
          Host "10.0.*.*"
            IdentityFile ~/.ssh/id_lxc
            UserKnownHostsFile=/dev/null
            StrictHostKeyChecking=no

    - name: Enable DHPC on lxcbr0
      blockinfile:
        block: LXC_DHCP_CONFILE=/etc/lxc/dhcp.conf
        marker: "# {mark} ANSIBLE MANAGED - LXC Install"
        path: /etc/sysconfig/lxc-net

    - name: Clone LXC Bash
      become: true
      become_user: "{{ user_login }}"
      git:
        repo: git@github.com:LongTermSupport/lxc-bash.git
        dest: /home/{{ user_login }}/Projects/lxc-bash

    - name: Add Aliases to bashrc file
      lineinfile:
        line: source /home/{{ user_login }}/Projects/lxc-bash/lxc-bash-completion.bash
        path: /home/{{ user_login }}/.bashrc

    - name: Increase System Limits
      blockinfile:
        path: /etc/sysctl.conf
        marker: "# {mark} ANSIBLE MANAGED - LXC Install"
        block: |
          fs.inotify.max_user_instances=8192
          fs.inotify.max_user_watches=524288
      notify: sysctl
      tags: sysctl

  handlers:
    - name: sysctl
      command: sysctl -p
          
      



