- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Basic packages
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - wget
          - bash-completion
          - htop

    - name: Passwordless Sudo
      copy:
        path: /etc/sudoers.d/{{ login_user }}.sudo.conf
        content: "{{ login_user }} ALL=(ALL) NOPASSWD: ALL"
        create: true

    - name: Vim Colours
      block:
        - name: Get Colourscheme
          get_url:
            url: https://raw.githubusercontent.com/ajmwagar/vim-deus/master/colors/deus.vim
            dest: /usr/share/vim/vimfiles/colors/deus.vim

        - name: Vim Configs
          blockinfile:
            marker: "\" {mark} Vim Colourscheme"
            block: colors deus
            path: /etc/vimrc.local
            create: true