- hosts: desktop
  name: Basic Configs
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Basic packages
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - wget
          - bash-completion
          - htop
      tags: packages

    - name: Passwordless Sudo
      blockinfile:
        dest: /etc/sudoers
        marker: "## {mark} passwordless sudo for {{ user_login}}"
        block: "{{ user_login }}    ALL=(ALL)    NOPASSWD: ALL"
        validate: visudo -cf %s

    - name: Vim Colours
      block:
        - name: Get Colourscheme
          get_url:
            url: https://raw.githubusercontent.com/ajmwagar/vim-deus/master/colors/deus.vim
            dest: /usr/share/vim/vimfiles/colors/deus.vim

        - name: Vim Configs
          blockinfile:
            marker: "\" {mark} Vim Colourscheme"
            block: colors deus
            path: /etc/vimrc.local
            create: true

    - name: Basic Bash Tweaks File
      copy:
        src: "{{ root_dir }}/files/etc/profile/zz_lts-fedora-desktop.bash"
        dest: /etc/profile.d/zz_lts-fedora-desktop.bash

    - name: Ensure Bash Tweaks are Loaded
      blockinfile:
        marker: "# {mark} ANSIBLE MANAGED: Bash Tweaks"
        block: source /etc/profile.d/zz_lts-fedora-desktop.bash
        path: "{{ item }}"
        create: false
      loop:
        - /root/.bashrc
        - /root/.bash_profile
        - /home/{{ user_login }}/.bashrc
        - /home/{{ user_login }}/.bash_profile

    - name: Copy SSH ID to root
      copy:
        remote_src: true
        src: /home/{{user_login}}/.ssh/{{item}}
        dest: /root/.ssh/{{item}}
        owner: root
        mode: 0600
      loop:
        - id
        - id.pub

    - name: Install YQ
      become: true
      shell: |
         wget https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_amd64 -O /usr/bin/yq && chmod +x /usr/bin/yq
      args:
        creates: /usr/bin/yq
      tags: yq

