- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Enable LXD Copr Repository
      shell:
        cmd: dnf copr enable ganto/lxc4 -y

    - name: Install Packages
      package:
        name:
        - lxc
        - lxc-templates

    - name: Add firewall rule for LXD to allow IP allocation and network access
      firewalld:
        zone: trusted
        state: enabled
        interface: lxdbr0
        permanent: yes

    - name: Setup Service
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - lxc-net
        - lxc
