- hosts: desktop
  name: RPM Fusion
  tasks:
    - name: Install RPM Fusion
      become: true
      shell: |
        dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
        dnf -y install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm