- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Enable LXD Copr Repository
      community.general.copr:
        name: "ganto/lxc4"

    - name: Install Packages
      package:
        name:
        - lxc
        - lxc-templates
        - libvirt

    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      selinux:
        policy: targeted
        state: permissive

    - name: Tell LXC to use libvirt bridge and avoid firewalld issues
      replace:
        path: /etc/lxc/default.conf
        regexp: lxcbr0
        replace: virbr0

    - name: Setup Service
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      with_items:
        - lxc
