- hosts: desktop
  become: true
  vars:
    root_dir: "{{ inventory_dir }}/../../"
  tasks:
    - name: Basic packages
      package:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - vim
          - wget
          - bash-completion
          - htop

    - name: Passwordless Sudo
      copy:
        dest: /etc/sudoers.d/{{ user_login }}.sudo.conf
        content: "{{ user_login }} ALL=(ALL) NOPASSWD: ALL"

    - name: Vim Colours
      block:
        - name: Get Colourscheme
          get_url:
            url: https://raw.githubusercontent.com/ajmwagar/vim-deus/master/colors/deus.vim
            dest: /usr/share/vim/vimfiles/colors/deus.vim

        - name: Vim Configs
          blockinfile:
            marker: "\" {mark} Vim Colourscheme"
            block: colors deus
            path: /etc/vimrc.local
            create: true

    - name: Basic Bash Tweaks
      copy:
        src: "{{ root_dir }}/files/etc/profile/zz_lts-fedora-desktop.bash"
        dest: /etc/profile.d/zz_lts-fedora-desktop.bash

